LiipImagineDemoBundle:
    resource: "@LiipImagineDemoBundle/Resources/config/routing.xml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
